language: c

sudo: required

addons:
  apt:
    packages:
    - dejagnu

cache:
  directories:
  - $HOME

env:
  - MESSAGE='its my message'
  - MESSAGE='its my other message'

stage: build
script: bash -c 'echo "$MESSAGE" > myfile; cat myfile'

jobs:
  include:
    - stage: dejagnu lookup
      env:
      - MESSAGE='its my other message'
      script: bash -c 'runtest my.exp'
    - stage: read
      script: bash -c 'cat myfile'