

jobs:
  include:
    - stage: write
      cache:
        directories:
        - $HOME
      script: bash -c 'echo "it is my message" > myfile; cat myfile'
    - stage: dejagnu lookup
      sudo: required
      addons:
        apt:
          packages:
          - dejagnu
      script: bash -c 'runtest my.exp'
    - stage: read
      cache:
        directories:
        - $HOME
      script: bash -c 'cat myfile'