
sudo: required
addons:
  apt:
    packages:
    - dejagnu

cache:
  directories:
  - $HOME

jobs:
  include:
    - stage: write
      script: bash -c 'echo "it is my message" > myfile; cat myfile'
    - stage: dejagnu lookup
      script: bash -c 'runtest my.exp'
    - stage: read
      script: bash -c 'cat myfile'